// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.19.4
// source: book.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BookServiceClient interface {
	GetBookData(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (BookService_GetBookDataClient, error)
}

type bookServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBookServiceClient(cc grpc.ClientConnInterface) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) GetBookData(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (BookService_GetBookDataClient, error) {
	stream, err := c.cc.NewStream(ctx, &BookService_ServiceDesc.Streams[0], "/book.BookService/GetBookData", opts...)
	if err != nil {
		return nil, err
	}
	x := &bookServiceGetBookDataClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BookService_GetBookDataClient interface {
	Recv() (*GetBookResponse, error)
	grpc.ClientStream
}

type bookServiceGetBookDataClient struct {
	grpc.ClientStream
}

func (x *bookServiceGetBookDataClient) Recv() (*GetBookResponse, error) {
	m := new(GetBookResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BookServiceServer is the server API for BookService service.
// All implementations must embed UnimplementedBookServiceServer
// for forward compatibility
type BookServiceServer interface {
	GetBookData(*GetBookRequest, BookService_GetBookDataServer) error
	mustEmbedUnimplementedBookServiceServer()
}

// UnimplementedBookServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (UnimplementedBookServiceServer) GetBookData(*GetBookRequest, BookService_GetBookDataServer) error {
	return status.Errorf(codes.Unimplemented, "method GetBookData not implemented")
}
func (UnimplementedBookServiceServer) mustEmbedUnimplementedBookServiceServer() {}

// UnsafeBookServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BookServiceServer will
// result in compilation errors.
type UnsafeBookServiceServer interface {
	mustEmbedUnimplementedBookServiceServer()
}

func RegisterBookServiceServer(s grpc.ServiceRegistrar, srv BookServiceServer) {
	s.RegisterService(&BookService_ServiceDesc, srv)
}

func _BookService_GetBookData_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetBookRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BookServiceServer).GetBookData(m, &bookServiceGetBookDataServer{stream})
}

type BookService_GetBookDataServer interface {
	Send(*GetBookResponse) error
	grpc.ServerStream
}

type bookServiceGetBookDataServer struct {
	grpc.ServerStream
}

func (x *bookServiceGetBookDataServer) Send(m *GetBookResponse) error {
	return x.ServerStream.SendMsg(m)
}

// BookService_ServiceDesc is the grpc.ServiceDesc for BookService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BookService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "book.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetBookData",
			Handler:       _BookService_GetBookData_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "book.proto",
}
